services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=yourpassword   # Change this to a strong password
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_SECURE_COOKIE=false                # Disable secure cookie for local development
      - TZ=America/New_York                     # Set your timezone if needed
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ../monitored-folder:/monitored_folder   # Mount the monitored folder for new documents
      - ../src:/project_src                     # Mount your source code
